version: '3.8'
services:
  postgresdb:
    image: postgres:15
    container_name: postgresdb
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: postgresdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - springboot-postgres-network

networks:
  springboot-postgres-network:
    driver: bridge

volumes:
  postgres-data: